### ISSUE TITLE
中文设置失败

### ISSUE THREAD

**Issue by shanezhiu** [jqhph/dcat-admin-docs#45]
## 环境
+ Larvel version: 8.x
+ dcat-admin version: 2.x
+ OS: debbian buser

## 问题

我按照文档[设置中文][1]

修改了我的config/app.php里的`locale=zh_CN`,但是界面并没有变成中文

查询laravel里相关issue,找到这个帖子[standard: locale should be zh_CN not zh-CN][2]

按照帖子里的描述，设置`locale=zh-CN`, 界面变成中文了。

我觉得文档需要指明这一点。

[1]:https://learnku.com/docs/dcat-admin/2.x/common-problem/8088#e69be3
[2]: https://github.com/Laravel-Lang/lang/issues/1073

**Comment by jqhph** [comment]
`2.x`版本就是`zh_CN`，文档也有说明，你是不是安装的`1.x`版本

**Comment by shanezhiu** [comment]
是我的问题，抱歉。

确实是`const VERSION = '1.7.8';`

我是执行` "dcat/laravel-admin": "*",`, 并不是安装最新的版本么？

**Comment by jackchang1025** [comment]
安装的是2.1.2-beta版本，设置locale=zh-CN失败

**Comment by jackchang1025** [comment]
上面当我放了个屁

**Comment by gityuh** [comment]
Larvel version: 9.x
dcat-admin version: 2.x

这个问题依然存在
