### ISSUE TITLE
繁体字库不全

### ISSUE THREAD

**Issue by yuantongziran** [jqhph/dcat-admin-docs#48]
语言我设置为繁体以后，很多繁体字显示不出来，就比如本身自带的/resources/lang/zh-TW/admin.php文件里，很多繁体字都显示不出来，我觉得是字体库的问题，但不知道要怎么更改dcat的显示字体。

**Comment by yuantongziran** [comment]
补充一下，1x和2x版本都有这个问题。
有一点很有意思，我在/config/admin.php里面设置'name'和'title'为一样的繁体字，结果是'title'显示正常，为网页上部的标题，而'name'就显示不出来，也就是/admin/auth/login登录页面的题目，而且更有意思的是，登录页面刷新的时候一开始是繁体字显示正常的，然后立马就变为简体字了。
还有一点，/config/app.php里语言选为繁体以后，整个框架的字的weight都小了，字变得很细。

**Comment by jqhph** [comment]
好的后续我优化一下这个功能

**Comment by davidfromtheeast** [comment]
> 好的后续我优化一下这个功能

拜托了~

P.S.
这个问题laravel-admin也有，当只加载doc的时候，繁体字都能正常显示，当加载上AdminLTE.min.css或者adminlte*.css以后，有的繁体字就显示成简体了。还有menu也都是简体。

**Comment by yuantongziran** [comment]
抱歉，繁体字不显示是我自己的问题，已经解决，和此框架无关。
就是繁体字还是显示的很细小，但也不是大问题。
